syntax = "proto3";

package protov;

import "google/protobuf/descriptor.proto";

option go_package = "autogen/options/rpc";

enum Formats {
  JSON     = 0;
  XML      = 1;
  PROTOBUF = 2;
}

message Client {
  string              url             = 1;
  string              method          = 2;
  map<string, string> headers         = 3;
  Formats             format          = 4;
  optional string     request_mapper  = 5;
  optional string     response_mapper = 6;
}

message Proxy {
  string url = 1;
}

message Definition {
  oneof client_or_proxy {
    Client client = 1;
    Proxy  proxy  = 2;
  }
}

extend google.protobuf.ServiceOptions {
  string address = 10000;
  string tags = 10001;
}

extend google.protobuf.MethodOptions {
  string alias = 10000;
  string tags = 10001;
  Definition definition = 10002;
}
